// ogre-window-event-utilities.cpp
//
// This file has been generated by the Okra Bindings Generator.
// You should not edit this file unless you know what you're doing.
// Any changes you've made directly to this file will not be retained
// when a new instance of this file is generated.
//
// author: Erik Winkels (aerique@xs4all.nl)
//
// See the LICENSE file in the Okra root directory for more info.
//
// This file was generated on: 2009-06-15 14:37:16.

#include "Ogre.h"
#include "okra.h"

using namespace Ogre;


// Prototypes

extern "C"
{
    void ogre_window_event_utilities_message_pump (WindowEventUtilities*);
    void ogre_window_event_utilities_add_window_event_listener (WindowEventUtilities*, RenderWindow*, WindowEventListener*);
    void ogre_window_event_utilities_remove_window_event_listener (WindowEventUtilities*, RenderWindow*, WindowEventListener*);
}


// Functions

// name: "messagePump"
// type: "void"
// args: NIL
//
void ogre_window_event_utilities_message_pump (WindowEventUtilities* ogre_window_event_utilities)
{
    ogre_window_event_utilities->messagePump();
}


// name: "addWindowEventListener"
// type: "void"
// args: (("RenderWindow*" . "window") ("WindowEventListener*" . "listener"))
//
void ogre_window_event_utilities_add_window_event_listener (WindowEventUtilities* ogre_window_event_utilities, RenderWindow* window, WindowEventListener* listener)
{
    ogre_window_event_utilities->addWindowEventListener(window, listener);
}


// name: "removeWindowEventListener"
// type: "void"
// args: (("RenderWindow*" . "window") ("WindowEventListener*" . "listener"))
//
void ogre_window_event_utilities_remove_window_event_listener (WindowEventUtilities* ogre_window_event_utilities, RenderWindow* window, WindowEventListener* listener)
{
    ogre_window_event_utilities->removeWindowEventListener(window, listener);
}


