;;;; typedefs.lisp
;;;;
;;;; This file has been generated by the Okra Bindings Generator.
;;;; You should not edit this file unless you know what you're doing.
;;;; Any changes you've made directly to this file will not be retained
;;;; when a new instance of this file is generated.
;;;;
;;;; author: Erik Winkels (aerique@xs4all.nl)
;;;;
;;;; See the LICENSE file in the Okra root directory for more info.
;;;;
;;;; This file was generated on: 2009-06-19 15:01:32.

(in-package :okra-bindings)


;;; Typedefs

(defctype rgba :uint32)
(defctype argb :uint32)
(defctype abgr :uint32)
(defctype bgra :uint32)
(defctype track-vertex-colour-type :int)
(defctype precise-real :double)
(defctype display-string :string)
(defctype uint32 :unsigned-int)
(defctype uint16 :unsigned-short)
(defctype uint8 :unsigned-char)
(defctype uint64 :unsigned-long-long)
(defctype uchar :unsigned-char)
(defctype ushort :unsigned-short)
(defctype uint :unsigned-int)
(defctype ulong :unsigned-long)
(defctype string-base :string)
(defctype resource-handle :unsigned-long)
(defctype background-process-ticket :unsigned-long)
(defctype scene-type-mask :uint16)
