;;;; [TMPL_VAR "file-name"]
;;;;
;;;; This file has been generated by the Okra Bindings Generator.
;;;; You should not edit this file unless you know what you're doing.
;;;; Any changes you've made directly to this file will not be retained
;;;; when a new instance of this file is generated.
;;;;
;;;; author: Erik Winkels (aerique@xs4all.nl)
;;;;
;;;; See the LICENSE file in the Okra root directory for more info.
;;;;
;;;; This file was generated on: [TMPL_VAR "date"].

(in-package :cl-user)

(defpackage :okra-system
  (:use :cl :asdf))

(in-package :okra-system)

(asdf:defsystem :okra-bindings
  :version "1.6.2.2"
  :components
  ((:module src-bindings
    :components
    ((:file "package")
     (:module ogre-lib :depends-on ("package")
      :components ((:file "ogre-lib")))
     (:file "enums" :depends-on ("package" ogre-lib))
     (:file "generics" :depends-on ("package" ogre-lib))
     (:file "typedefs" :depends-on ("package" ogre-lib))
[TMPL_LOOP "files"]     (:file "[TMPL_VAR "file"]" :depends-on ("package" ogre-lib "generics" "enums" "typedefs"))
[/TMPL_LOOP]     (:module handwritten :depends-on ("package" ogre-lib)
      :components ((:file "misc") (:file "moc"))))))
  :depends-on (:cffi :okra-common))
