;;;; [TMPL_VAR "file-name"]
;;;;
;;;; This file has been generated by the Okra Bindings Generator.
;;;; You should not edit this file unless you know what you're doing.
;;;; Any changes you've made directly to this file will not be retained
;;;; when a new instance of this file is generated.
;;;;
;;;; author: Erik Winkels (aerique@xs4all.nl)
;;;;   note: For now, this file exists to silence a CL implementation about
;;;;         implicitly generated generic functions.  In the future
;;;;         documentation from the Doxygen files will be added.
;;;;
;;;; See the LICENSE file in the Okra root directory for more info.
;;;;
;;;; This file was generated on: [TMPL_VAR "date"].

(in-package :okra-bindings)


;;; Generic Functions

[TMPL_LOOP "generics"](defgeneric [TMPL_VAR "name"] (this[TMPL_IF "overloaded"] &optional[/TMPL_IF][TMPL_LOOP "args"] [TMPL_VAR "arg-name"][/TMPL_LOOP]))

[/TMPL_LOOP]
