# [TMPL_VAR "file-name"]
#
# This file has been generated by the Okra Bindings Generator.
# You should not edit this file unless you know what you're doing.
# Any changes you've made directly to this file will not be retained
# when a new instance of this file is generated.
#
# author: Erik Winkels (aerique@xs4all.nl)
#
# See the LICENSE file in the Okra root directory for more info.
#
# This file was generated on: [TMPL_VAR "date"].

set(LIBOKRA_SOURCE_FILES
    "../../3rd-party/moc/CollisionTools.cpp"
    "../src/handwritten/misc.cpp" "../src/handwritten/moc.cpp"
   [TMPL_LOOP "files"] "../src/[TMPL_VAR "file"]"[/TMPL_LOOP])

if (APPLE)
  #set(CMAKE_OSX_ARCHITECTURES i386) Appears to fail on 10.6
  set(BUILD_SHARED_LIBS ON)
  set(CMAKE_CXX_FLAGS "-arch i386 -m32 -include Carbon/Carbon.h
      ${CMAKE_CXX_FLAGS}")
  find_library(OGRE_LIBRARY Ogre "/Users/Si/Library/SDKs/OgreSDK/Dependencies")
  include_directories("${OGRE_LIBRARY}/Headers")
endif (APPLE)

add_library(okra ${LIBOKRA_SOURCE_FILES})

target_link_libraries(okra ${OGRE_LIBRARY})
